//
// Created by tom on 25-10-15.
//

#ifndef GATESERVER_ERRORCODE_H
#define GATESERVER_ERRORCODE_H

enum ErrorCode {
    SUCCESS = 0,
    JSON_ERROR = 1001,
    RPC_ERROR = 1002,
    VERIFYCODE_EXPIRED = 1003,
    VERIFYCODE_ERROR = 1004,
    REGISTER_USER_ERROR = 1005,
    RESET_PWD_ERROR = 1006,
    USER_LOGIN_ERROR = 1007
};

#endif //GATESERVER_ERRORCODE_H
